# -*- coding: utf-8 -*-
"""Aula_15_resolução

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14FAYwoD3g1pxstqomx_MM22VnaHcP2W5
"""

'''Módulos em Python são arquivos que contêm um conjunto de funções,
variáveis e classes que você pode usar em seus programas Python.
Eles permitem organizar e reutilizar código, tornando seus programas
mais eficientes e mais fáceis de manter. qui estão alguns módulos Python:'''

'''1. math:
   O módulo math fornece funções matemáticas, como operações de aritmética,
trigonometria, exponenciação, raiz quadrada, etc.'''

   import math
   print(math.sqrt(25))  # Calcula a raiz quadrada de 25


'''2. random:
   O módulo random permite gerar números aleatórios e é útil para jogos,
simulações e outras aplicações que envolvem aleatoriedade.'''

   import random
   print(random.randint(1, 6))  # Gera um número aleatório entre 1 e 6


'''3. os:
   O módulo os fornece funções para interagir com o sistema operacional,
permitindo que você manipule diretórios, arquivos e execute comandos do sistema.'''

   import os
   print(os.getcwd())  # Obtém o diretório de trabalho atual


'''4. datetime:
   O módulo datetime oferece classes e funções para trabalhar com datas e horas.'''

   from datetime import datetime
   data_atual = datetime.now()
   print(data_atual)


'''5. json:
   O módulo json é usado para trabalhar com dados JSON, que são comuns
em comunicação de dados na web.'''

   import json
   dados = '{"nome": "João", "idade": 30}'
   objeto = json.loads(dados)
   print(objeto["nome"])


'''Python possui uma vasta biblioteca padrão com muitos outros módulos que
podem ser explorados à medida que você ganha experiência com a linguagem. Além disso,
você também pode criar seus próprios módulos para organizar seu código em
projetos maiores.'''

import math
   print(math.sqrt(25)) # Calcula a raiz quadrada de 25

import random
print(random.randint(1, 6)) #Gera um número aleatório entre 1 e 6

import os
print(os.getcwd())  # Obtém o diretório de trabalho atual

from datetime import datetime
data_atual = datetime.now()
print(data_atual)  #

import json
dados = '{"nome": "João", "idade": 30}'
objeto = json.loads(dados)
print(objeto["nome"])

"""Exercício 1:
Calcule a raiz quadrada de um número inteiro inserido pelo usuário usando o módulo math
"""

import math
raiz_quadrada = math.sqrt(36)
print(raiz_quadrada)

"""Exercício 2:
Calcule o valor absoluto de um número decimal inserido pelo usuário usando o módulo math
"""

import math
numero_absoluto = math.fabs(6.547)
print(numero_absoluto)

"""Exercício 3:
Arredonde um número decimal inserido pelo usuário para o inteiro mais próximo
usando o módulo math
"""

import math
n = 5.564
print(f'0 valor de {n} para cima é: {math.ceil(n)}')

"""Exercício 4:
Calcule o seno de um ângulo em graus inserido pelo usuário usando o módulo math.
"""

import math
angulo_radianos = math.radians(90)
seno = math.sin(angulo_radianos)
print(seno)

import math

# Exercício 1:
# Calcule a raiz quadrada de um número inteiro inserido pelo usuário usando o módulo math

# n  = int(input("Digite um número ->  "))
# raiz =  math.sqrt(n)
# print(raiz)



# Exercício 2:
# Calcule o valor absoluto de um número decimal inserido pelo usuário usando o módulo math

# v =  int(input("Digite >"))
# vb = math.fabs(v)
# print(vb)



# Exercício 3:
# Arredonde um número decimal inserido pelo usuário para o inteiro mais próximo
# usando o módulo math

# n = float(input())
# dc =  math.ceil(n)
# print(dc)


# Exercício 4:
# Calcule o seno de um ângulo em graus inserido pelo usuário usando o módulo math.

ang =  float(input("Digite"))
radio = math.radians(ang)
seno =  math.sin(ang)
print(radio, seno)